"""add unique to symbol history

Revision ID: 2bb0c20b7e84
Revises: 4eb82fa77b19
Create Date: 2023-06-12 12:07:22.476285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bb0c20b7e84'
down_revision = '4eb82fa77b19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
