"""init revision

Revision ID: 4eb82fa77b19
Revises: 
Create Date: 2023-06-11 22:54:15.107475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eb82fa77b19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symbol_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbol_master_exchange'), 'symbol_master', ['exchange'], unique=False)
    op.create_index(op.f('ix_symbol_master_id'), 'symbol_master', ['id'], unique=False)
    op.create_index(op.f('ix_symbol_master_ticker'), 'symbol_master', ['ticker'], unique=False)
    op.create_table('third_party_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('website')
    )
    op.create_index(op.f('ix_third_party_tokens_id'), 'third_party_tokens', ['id'], unique=False)
    op.create_table('symbol_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('symbol_master_id', sa.Integer(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['symbol_master_id'], ['symbol_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbol_history_id'), 'symbol_history', ['id'], unique=False)
    op.create_index(op.f('ix_symbol_history_open'), 'symbol_history', ['open'], unique=False)
    op.create_index(op.f('ix_symbol_history_symbol_master_id'), 'symbol_history', ['symbol_master_id'], unique=False)
    op.create_index(op.f('ix_symbol_history_timestamp'), 'symbol_history', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_symbol_history_timestamp'), table_name='symbol_history')
    op.drop_index(op.f('ix_symbol_history_symbol_master_id'), table_name='symbol_history')
    op.drop_index(op.f('ix_symbol_history_open'), table_name='symbol_history')
    op.drop_index(op.f('ix_symbol_history_id'), table_name='symbol_history')
    op.drop_table('symbol_history')
    op.drop_index(op.f('ix_third_party_tokens_id'), table_name='third_party_tokens')
    op.drop_table('third_party_tokens')
    op.drop_index(op.f('ix_symbol_master_ticker'), table_name='symbol_master')
    op.drop_index(op.f('ix_symbol_master_id'), table_name='symbol_master')
    op.drop_index(op.f('ix_symbol_master_exchange'), table_name='symbol_master')
    op.drop_table('symbol_master')
    # ### end Alembic commands ###
